### ISSUE TITLE
Modify README to point users to Anaconda Python instead of normal python.

### ISSUE THREAD

**Issue by cdgreenidge** [cdgreenidge/leabra7#46]
Hey Noam,

I just realized that the README points users to the Hitchiker's Guide to Python for the Python installation instructions. Since we moved our packaging to Anaconda, we actually want them to install the Anaconda python distribution (https://conda.io/docs/user-guide/install/download.html)

Could you update the README (again, sorry!) to point them there?

**Comment by noammiller** [comment]
Fixed in fix-readme branch.
